export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import {client} from "../../sanity/lib/client"
export default async function RootLayout({ children }) {

  const query=`*[
    _type=="Product" 
   ]{
     name,
     "description":description[0].children[0].text,
       condition,
         image,
         instock,
         "slug":slug.current
   }`
   const products=await client.fetch(query)
   console.log(client)  ;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
